---
title: "About"
author: "Lynette, Jingxuan, Manqi, Yixi"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

## Introduction: 

Movies have become a big part of everyday life worldwide and their popularity grow with time. In this project, we intend to explore the explanatory factors for the total gross, review scores and opening gross of movies that were released in North America from 2006 to 2016. We attempt to use linear regression model for each of three interested outcomes including total gross, review scores (metacritic review score) and opening gross. Our goal of analysis is to look into the relationship between a variable such as genre, actors/actresses, production company, director and review scores and each of our interested outcome variables. Mainly, there are three outcomes including total gross, review scores (metacritic review score) and opening gross that we are interested in for each movie in North America that was released from 2006 to 2016. 

## Data and methods:
* **Data source:**
    + [Domestic Box office:](http://www.boxofficemojo.com/yearly/chart/?yr=2014&view=releasedate&view2=domestic&sort=gross&order=DESC&&p=.htm) (Only use movies with total sales that ranked top 100)
    + [06-16 movie:](https://www.kaggle.com/PromptCloudHQ/imdb-data)

* **Data Description:** 
    + The box office data was obtained by using a for-loop that scraped movies with total sales that ranked top 100 in each year from 2006 to 2016, resulting in a data frame containing 1100 rows and five variables: movie titles, studio, total gross, opening gross and released year.
    + The movie dataset includes 1,000 most popular movies on IMDB (http://www.imdb.com/) from 2006 to 2016. The data points included are: Title, Genre, Description, Director, Actors, Year, Runtime, Rating, Votes, Revenue, Metascore for each movie. 

* **Data cleaning and scraping:**
    + Firstly, we wrote a for-loop to scape the box office dataset from the online source which includes movies with total box office that ranked top 100 in each year from 2006 to 2016. After we changed the names of box office dataset for consistency, we joined the box office dataset with the movie dataset obtained from kaggle by the movie names. 
    + Next, we cleaned our combined dataset. We decided to keep the total gross column and replaced NA in total gross with the values in Revenue column in movie dataset. Also, we divided the total gross by 10^6 to reduce the number of zeros in that column. Furthermore, we separated the actor column into four new columns for later analysis purpose. And then separate the genre into three columns for later data analysis (code is available if unveiling the code chunk).


```{r, echo=FALSE}
library(dplyr)
library(tidyverse)
library(httr)
library(rvest)
library(stringr)
library(forcats)
library(viridis)
library(readr)
library(tidytext)
library(rvest)
library(janitor)
library(haven)
library(DT)
library(plotly)
# read IMDB data from Kaggle
movie = read.csv("./data/IMDB-Movie-Data.csv")

# read boxoffice data from internet
url_base = "http://www.boxofficemojo.com/yearly/chart/?view=releasedate&view2=domestic&yr="

# create url strings for 2006 - 2016 boxoffice data; only include movies with top 100 total gross in each year. 
urls = str_c(url_base, 2006:2016, "&sort=gross&order=DESC&p=.htm")
output = vector("list", 11)

# create for loop to generate the 2006 - 2016 boxoffice dataframe
boxoffice = NULL
for (i in 1:11) {

output[[i]] = read_html(urls[[i]])

output[[i]] %>% 
html_nodes(css = "table")

box_office_year = (output[[i]] %>% html_nodes(css = "table"))[[7]] %>%
  html_table(fill = TRUE) 
  
colnames(box_office_year) = box_office_year[1,]
colnames(box_office_year)[2] = "movie_title"
colnames(box_office_year)[3] = "studio"
colnames(box_office_year)[4] = "total_gross"
colnames(box_office_year)[5] = "theaters"
colnames(box_office_year)[6] = "opening"
colnames(box_office_year)[7] = "theaters_opening"  

box_office_year = box_office_year %>% 
  dplyr::select(movie_title, studio, total_gross, opening) %>% 
  .[3:102,] %>%
  mutate(year = 2005 + i)
    
boxoffice = bind_rows(boxoffice, box_office_year)  
}

set.seed(1)
# renmae the movie_title in movie dataset in order to join two datasets
movie_rename= movie %>% 
  clean_names() %>% 
  rename("movie_title" = "title",
         "review_score" = "metascore")

# joining two datasets; tidy data set
movie_with_boxoffice = left_join(movie_rename, boxoffice, by=c("movie_title", "year")) %>% 
  rename("open_gross" = "opening")  

# Replace NA values in total_gross with the revenue column in movie dataset
total_gross_na = is.na(movie_with_boxoffice$total_gross)

movie_with_boxoffice$total_gross[total_gross_na] =  movie_with_boxoffice$revenue_millions[total_gross_na]*10^6

# eliminate $sign and "," of the total gross and open gross, remove rows with review scores is NA:
movie_with_boxoffice = movie_with_boxoffice %>% 
  mutate(total_gross = gsub("\\$", "", total_gross),
         total_gross = gsub(",", "", total_gross),
         total_gross = as.numeric(total_gross),
         open_gross = gsub("\\$", "", open_gross),
         open_gross = gsub(",", "", open_gross),
         open_gross = as.numeric(open_gross)) %>% 
  mutate(total_gross_millions = total_gross / 10^6,
         open_gross_millions = open_gross / 10^6,
         actors_sep = actors,
         genre_sep = genre) %>% 
  select(-total_gross, -revenue_millions, -open_gross) %>% 
  separate(., actors_sep, c("actor1","actor2", "actor3", "actor4"), sep=",") %>% 
  separate(genre_sep, into = c("genre1", "genre2", "genre3"), sep = ",")
```





* **Statistical analysis:**
    + In this project, we mainly interested in analyzing the relationship between explanatory variable and outcome using linear regression model, specifically simple linear regression. Specifically, we hypothesized that there is a linear relationship between th explanatory variable(s) and outcome. Simple linear regression is a statistical method that allows us to summarize and study relationships between two variables. Multiple linear regression is also one type of linear regression model and contains more than one explanatory variables. Both simple linear regression and multiple linear regression are used to explore the relationship between predictor variable(s) and the interested outcome. 
    + lm function is used to fit a linear regression model to the interested explanatory variable(s) and dependent outcome. For simplicity, we used the P value (Pr>|t|) in each summarized lm() output to draw conclusion about whether the variable is significant predictor of the outcome. Commonly, we used 0.05 significance level to make conclusions. Moreover, lm function gives us the estimated coefficients (slope) for the linear model, which can used to predict how the outcome will change in response to the increase of the predictor.
    + ANOVA is used when the explanatory variable has different levels/categories. Firstly, we used the ANOVA function to determine whether the variable as a whole is a significant predictor. Then we can explore the estimated coefficient for each level of that variable by using lm function. The estimated coefficient indicate how the outcome will change in response to the presence of a certain level/category of the predictor. 


## Results:

### Total gross as outcome

* **Objective:** In this part of the analysis, we are specifically interested in total gross as the outcome. Moreover, we attempt to test whether review score, genre, actor, director and production company could be the predictors for the total gross (movies without total gross are omitted).
    + **Multiple linear regression model:** From the hypothesis testing and analysis presented above, we know that production company, director and review scores are statistical significant predictors for the total gross. Then we try a multiple linear regression model with all these significant predictors included. Since we include both continuous and categorical predictors in the model, we need to use ANOVA table to test whether each of the predictor is statistically significant.



* **Results:**

    + **Review score:** At 0.05 significance level, we can say that there is a linear association between total gross and review scores. The best fitting linear line is $y = 34.04 + 0.85x$. For every one score increase in metascore, we expected the increase of total gross to be 0.85 (in millions).

    + **Genre:** At 0.001 significance level, we can say that genre is a significant predictor of the total box office. Then the estimated coefficient for each genre is given in the data table, which shows us how the total gross will change when the movie falls into one of the genres.

    + **Director:** At 0.001 significance level, we can say that director is a significant predictor of the total box office. Then the estimated coefficient for each director is given in the data table, which shows us how the total gross will change related to the director of the movie. 

    + **Actors/actresses:** At 0.05 significance level, we fail to conclude the linear association since actor/actress is not a significant predictor of the total gross. 

    + **Production company:** At 0.001 significance level, we can conclude that production company is a significant predictor of the total box office. Then the estimated coefficient for each production company is given in the data table, which shows us how the total gross will change related to the production company of the movie. 



* **Results of Multiple linear regression model:** By using the ANOVA function, we can see that when put these four predictors into one regression mode, all of these four predictors are still statistically significant at 0.05 significance level. Then the best fitted coefficients estimate is obtained by using the lm function, which tells us how the total gross will change when one of the category presents or has certain values while holding other covariates constant.


***
***


### Review score as outcome

* **Objective:** And in this part of the analysis, we are focusing on review score as the outcome. We are interested in whether total gross, genre, actor, director and film studio could be the predictors for the review score (movies without review score are omitted).



* **Results:**

    + **Total gross:** At 0.05 significance level, we can say that the positive association between review scores and boxoffice is significant. With every million increase in boxoffice, the expected review score will increase by 0.023 on average.

    + **Genre:** The positive association between review scores and genre is significant. There are 12 types of genres are significant predictor for review score. Genres with top three high estimate of review scores are history, animation and biography.

    + **Director:** At 0.05 significance level, director has significant association with review score. Then the estimated coefficient for each director is given in the data table, which shows us how the review score will change related to the director of the movie. 

    + **Actors/actresses:** At 0.05 significance level, actors has significant association with review score. Then the estimated coefficient for each actor is given in the data table, which shows us how the review score will change related to the director of the movie. 

    + **Production company:** At 0.05 significance level, we can conclude that film studio is a significant predictor of the review score. Then the estimated coefficient for each studio is given in the data table, which shows us how the review score will change related to the production company of the movie. 
    
***
***

### Open gross as outcome

* **Objective:** In this part of the analysis, we are specifically interested in open gross as the outcome. Moreover, we attempt to test whether review score, genre, actor, and director could be the predictors for the open gross. What's more, we use open gross as a predictor of total gross.
    + **Multiple linear regression model:** From the hypothesis testing and analysis presented above, we know that rating ,genre and director are statistical significant predictors for the open gross. Then we try a multiple linear regression model with all these significant predictors included. Since we include both continuous and categorical predictors in the model, we need to use ANOVA table to test whether each of the predictor is statistically significant.



* **Results of Multiple linear regression model:**  Finally, I fit a overall linear regression between open gross and review score, rating, total gross millions.The regression model is open_gross = 36.44 -0.23review_score - 3.49rating + 0.30total_gross_millions.



## Discussion:

* When total gross is the interested outcome, review score, genre, director and production company are significantly predictors for the total gross, whereas actors/actresses are not significant predictors for the total gross. In the multiple linear regression model, review score, genre, director and production company are still statistically significant. This analysis provides the insight of how each potential explanatory factors relate to the total gross of movies, which can be further explore how to build the complex model to predict the total gross of movies.

*   When open gross is the interested outcome, review score, genre, director and rating are all non-significantly predictors for the open gross. In the multiple linear regression model, review score, rating, total gross are still statistically significant. This analysis provides the insight of how each potential explanatory factors relate to the open gross of movies, which can be further explore how to build the complex model to predict the open gross of movies.

**Fun Finding! :**

*  Directors with top three high review scores are Barry Jenkins, Kenneth Lonergan and Todd Haynes. They directed Moonlight, Manchester by the Sea and Carol respectively, which are all movies with good reputation and been nominated by Oscar. It's not hard to think they have high review score! :)

*  It is surprising that top film studios like Warner Bros and Universal Studio have are negatively associated with review score, which means if the film is made by these film, it may have a lower review score! The reason behind this phenomenon may be top studios produce hundreds of movie each year and not all of them got good reputaion, which lower the eastimate of review scores.

*  Director with really high box office doesn’t always means that he directed good movies. Michael Bay, for example, ranked as 4th director with best box-office, whereas the mean review score of his movies is only 43.8, which is lowest among top 10 director with best box office.

*  The two sets of Dark Knites seems to be very successful, because they both ranked top 10 in the opening gross. What's more, they are both directed by Christopher Nolan. He is indeed a good director.

*   We have some fun findings about movies' parameters according to years. We create a shiny.app for displaying these results, and the link is [here](https://caimanqi.shinyapps.io/shiny_dashboard_template/)
