---
title: "final project_1"
---

```{r packages}
library(dplyr)
library(tidyverse)
library(httr)
library(rvest)
library(stringr)
library(forcats)
library(viridis)
library(readr)
library(tidytext)
library(rvest)
library(janitor)
library(haven)
library(DT)
```

# Prepare datasets
```{r data_prepare, include=FALSE}
# read IMDB data from Kaggle
movie = read.csv("./data/IMDB-Movie-Data.csv")

# read boxoffice data from internet
url_base = "http://www.boxofficemojo.com/yearly/chart/?view=releasedate&view2=domestic&yr="

# create url strings for 2006 - 2016 boxoffice data; only include movies with top 100 total gross in each year. 
urls = str_c(url_base, 2006:2016, "&sort=gross&order=DESC&p=.htm")
output = vector("list", 11)

# create for loop to generate the 2006 - 2016 boxoffice dataframe
boxoffice = NULL
for (i in 1:11) {

output[[i]] = read_html(urls[[i]])

output[[i]] %>% 
html_nodes(css = "table")

box_office_year = (output[[i]] %>% html_nodes(css = "table"))[[7]] %>%
  html_table(fill = TRUE) 
  
colnames(box_office_year) = box_office_year[1,]
colnames(box_office_year)[2] = "movie_title"
colnames(box_office_year)[3] = "studio"
colnames(box_office_year)[4] = "total_gross"
colnames(box_office_year)[5] = "theaters"
colnames(box_office_year)[6] = "opening"
colnames(box_office_year)[7] = "theaters_opening"  

box_office_year = box_office_year %>% 
  select(movie_title, studio, total_gross, opening) %>% 
  .[3:102,] %>%
  mutate(year = 2005 + i)
    
boxoffice = bind_rows(boxoffice, box_office_year)  
}
```

```{r combine and tidy dataset}
set.seed(1)
# renmae the movie_title in movie dataset in order to join two datasets
movie_rename= movie %>% 
  clean_names() %>% 
  rename("movie_title" = "title",
         "review_score" = "metascore")

# joining two datasets; tidy data set
movie_with_boxoffice = left_join(movie_rename, boxoffice, by=c("movie_title", "year")) %>% 
  rename("open_gross" = "opening")  

# Replace NA values in total_gross with the revenue column in movie dataset
total_gross_na = is.na(movie_with_boxoffice$total_gross)

movie_with_boxoffice$total_gross[total_gross_na] =  movie_with_boxoffice$revenue_millions[total_gross_na]*10^6

# eliminate $sign and "," of the total gross and open gross, remove rows with review scores is NA:
movie_with_boxoffice = movie_with_boxoffice %>% 
  mutate(total_gross = gsub("\\$", "", total_gross),
         total_gross = gsub(",", "", total_gross),
         total_gross = as.numeric(total_gross),
         open_gross = gsub("\\$", "", open_gross),
         open_gross = gsub(",", "", open_gross),
         open_gross = as.numeric(open_gross)) %>% 
  mutate(total_gross_millions = total_gross / 10^6,
         open_gross_millions = open_gross / 10^6) %>% 
  select(-total_gross, -revenue_millions, -open_gross) 
  
movie_with_boxoffice_sep = movie_with_boxoffice %>% 
  separate(., actors, c("actor1","actor2", "actor3", "actor4"), sep=",") %>% 
  separate(genre, into = c("genre1", "genre2", "genre3"), sep = ",")
```


```{r}
##Top 10 movies with best box-office 
movie_with_boxoffice %>% 
  group_by(movie_title, director) %>% 
  summarize(box_movie = sum(total_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()

##Top 10 movies with best opening box-office 
movie_with_boxoffice %>% 
  group_by(movie_title, director) %>% 
  summarize(box_movie = sum(open_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()
```

```{r}
##Director:  The top 10 ranked director who contributed most box-office
movie_with_boxoffice %>% 
  group_by(director) %>% 
  summarize(box_movie = sum(total_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()

##Director:  The top 10 ranked director who contributed most opening box-office
movie_with_boxoffice %>% 
  group_by(director) %>% 
  summarize(box_movie = sum(open_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()
```

```{r}
##Type: The top 10 ranked type of movies who contributed most box-office
movie_with_boxoffice %>% 
  mutate(genre = as.character(genre)) %>% 
  unnest_tokens(word,genre) %>% 
  mutate(genre = word) %>% 
  group_by(genre)%>%
  summarize(box_movie = sum(total_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()

##Type: The top 10 ranked type of movies with best opening box-office
movie_with_boxoffice %>% 
  mutate(genre = as.character(genre)) %>% 
  unnest_tokens(word,genre) %>% 
  mutate(genre = word) %>% 
  group_by(genre)%>%
  summarize(box_movie = sum(open_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()
```

```{r}
##Actor/Actress:  The top 10 ranked actor/actress with best box-office
movie_total_gross_with_review_narm %>% 
  separate(actors, into = c("remove", "actor"), sep = ",") %>% 
  select(-remove) %>% 
  group_by(actor) %>%
  summarize(box_movie = sum(total_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()

#####Actor/Actress:  The top 10 ranked actor/actress with best opening box-office
movie_total_gross_with_review_narm %>% 
  separate(actors, into = c("remove", "actor"), sep = ",") %>% 
  select(-remove) %>% 
  group_by(actor) %>%
  summarize(box_movie = sum(total_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()
```

```{r}
##Production company:  The top 10 ranked production company  with best box-office
movie_total_gross_with_review_narm %>% 
  group_by(studio) %>%
  na.omit() %>% 
  summarize(box_movie = sum(total_gross_millions)) %>% 
  arrange(desc(box_movie)) %>% 
  head(10) %>% 
  knitr::kable()
```

sentiment analysis
```{r}
movie_analysis =  movie %>%  
  clean_names() %>% 
  mutate(inspection_num = row_number()) %>% 
  mutate(description = as.character(description)) %>% 
  select(title, description, inspection_num, rating)

inspection_words = movie_analysis %>% 
  unnest_tokens(word, description)

data(stop_words)

inspection_words = anti_join(inspection_words, stop_words)
```

```{r}
##most frequent word
inspection_words %>% 
  filter(rating >= "8.0") %>% 
  count(word, sort = TRUE) %>% 
  top_n(10)

##low review
inspection_words %>% 
  filter(rating <= "3.0") %>% 
  count(word, sort = TRUE) %>% 
  top_n()
```


```{r}
bing_sentiments = get_sentiments("bing")

inspection_sentiments = inspection_words %>% 
  inner_join(., bing_sentiments) %>% 
  count(inspection_num, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative) %>% 
  select(inspection_num, sentiment)

inspection_sentiments = 
  right_join(movie_analysis, inspection_sentiments, 
             by = "inspection_num")

inspection_sentiments %>% 
  mutate(inspection_num = factor(inspection_num),
    inspection_num = fct_reorder(inspection_num, sentiment)) %>% 
  ggplot(aes(x = inspection_num, 
             y = sentiment, fill = rating, color = rating)) + 
  geom_bar(stat = "identity") + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_fill_viridis(discrete = FALSE) + 
  scale_color_viridis(discrete = FALSE)
```


