---
title: "Overview"
---
**Word Cloud for Movie Names from 2006 to 2016**
```{r echo = FALSE, fig.align='center', warning=FALSE, message=FALSE}
# Install
# install.packages("tm")  # for text mining
# install.packages("SnowballC") # for text stemming
# install.packages("wordcloud") # word-cloud generator 
# install.packages("RColorBrewer") # color palettes
# Load
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library(tidyverse)

# create text files containing movie names in order to make a word cloud
# movies_names = read_csv("IMDB-Movie-Data.csv") %>% 
#   select(Title) %>% 
#   write.table(., "movies_names.txt", sep="\t")

text = as.character(readLines("./data/movies_names.txt"))
docs = tm::Corpus(tm::VectorSource(text))
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)



set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```




* This website contains the final project for [Jeff Goldsmith's Data Science I class](http://jeffgoldsmith.com/DSI/index.html) in the Department of Biostatistics at Columbia University. 

***

> Group Members: 

  * Yue(Lynette) Pan (yp2463) 1
  * Yixi Xu (yx2450) 2
  * Manqi Cai (mc4433) 3
  * Jingxuan He (jh3909) 4
  
>  Overview of the project goals and motivation.:

* In this project, we intend to explore the indicating factors of the total gross, review scores and opening gross for movies that were released in North America from 2006 to 2016.
* Mainly, there are three outcomes that we are interested in including **total gross, review scores (metacritic review score) and opening gross** for each movie in North America that was released from 2006 to 2016.
* Specifically, our exploratory analysis is based upon the 

> Motivation

* Our moviation is really intuitive and simple. Since our members are movie-lovers, we would like to know if there is any factors that could potential be significant predictor of the interested outcome.

> Initial questions and New Questions:

* At the beginning of our project, we intend to explore the relationship between review score , genre, actor, director and each of interested outcome, namely **total gross, review scores (metacritic review score) and opening gross**.

* As the project progressed, we found that some of factors may be a significant predictor, whereas different levels within that factor may not be statistically significant. 

> Data

* Data Source:
    + [Box office](http://www.boxofficemojo.com/yearly/chart/?yr=2014&view=releasedate&view2=domestic&sort=gross&order=DESC&&p=.htm) 
    + [06-16 movie](https://www.kaggle.com/PromptCloudHQ/imdb-data)

  
  
* Scapring process & cleaning:
    + Firstly, we use the 06-16 movie dataset from kaggle and scrape the box office data from a [online source]((http://www.boxofficemojo.com/yearly/chart/?yr=2014&view=releasedate&view2=domestic&sort=gross&order=DESC&&p=.htm)).
    + For the cleaning of the scraped data, we wrote a function to loop through urls that contains box office data from 2006 to 2016. We extracted the data table and formated in the way that could be combined and joined with our dataset from kaggle.

> Exploratory analyasis:

* We make plots for: 
    + top 10 ranked director  with best box-officehe 
    + top 10 ranked type of movies with best box-office
    + top 10 ranked actor/actress with best box-office
    + top 10 ranked production company with best box-office
  
  
> Additional analysis:

* We use lm function and anova function to test if the factor that we are tested is a statistical significant predictor of the interested outcome.

* If the predictor is contious, we will fit a linear regression line to the data; if the predictor is categorical and contains many levels, we will use plotly to display the difference among the levels of the predictor with regard to the interested outcome.

> Discussion

* For the total gross, 
    + There is a linear relationship between total gross (outcome) and review score (predictor). 
    + Director is a significant predictor of total gross.
    + Actor is not a significant predictor of total gross.
  
  
  



