---
title: "p8105_final_jh3909"
author: "Jingxuan He"
date: "November 20, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(dplyr)
library(tidyverse)
library(httr)
library(rvest)
library(janitor)
library(stringr)
library(ggplot2)
library(hexbin)
library(plotly)
library(knitr)
```

# Prepare datasets
```{r data_prepare, include=FALSE}
# read IMDB data from Kaggle
movie = read.csv("IMDB-Movie-Data.csv")

# read boxoffice data from internet
url_base = "http://www.boxofficemojo.com/yearly/chart/?view=releasedate&view2=domestic&yr="

# create url strings for 2006 - 2016 boxoffice data; only include movies with top 100 total gross in each year. 
urls = str_c(url_base, 2006:2016, "&sort=gross&order=DESC&p=.htm")
output = vector("list", 11)

# create for loop to generate the 2006 - 2016 boxoffice dataframe
boxoffice = NULL
for (i in 1:11) {

output[[i]] = read_html(urls[[i]])

output[[i]] %>% 
html_nodes(css = "table")

box_office_year = (output[[i]] %>% html_nodes(css = "table"))[[7]] %>%
  html_table(fill = TRUE) 
  
colnames(box_office_year) = box_office_year[1,]
colnames(box_office_year)[2] = "movie_title"
colnames(box_office_year)[3] = "studio"
colnames(box_office_year)[4] = "total_gross"
colnames(box_office_year)[5] = "theaters"
colnames(box_office_year)[6] = "opening"
colnames(box_office_year)[7] = "theaters_opening"  

box_office_year = box_office_year %>% 
  select(movie_title, studio, total_gross, opening) %>% 
  .[3:102,] %>%
  mutate(year = 2005 + i)
    
boxoffice = bind_rows(boxoffice, box_office_year)  
}
```

```{r combine and tidy dataset}
set.seed(1)
# renmae the movie_title in movie dataset in order to join two datasets
movie_rename= movie %>% 
  clean_names() %>% 
  rename("movie_title" = "title",
         "review_score" = "metascore")

# joining two datasets; tidy data set
movie_with_boxoffice = left_join(movie_rename, boxoffice, by=c("movie_title", "year")) %>% 
  rename("open_gross" = "opening")  

# Replace NA values in total_gross with the revenue column in movie dataset
total_gross_na = is.na(movie_with_boxoffice$total_gross)

movie_with_boxoffice$total_gross[total_gross_na] =  movie_with_boxoffice$revenue_millions[total_gross_na]*10^6

# eliminate $sign and "," of the total gross and open gross, remove rows with review scores is NA:
movie_with_boxoffice = movie_with_boxoffice %>% 
  mutate(total_gross = gsub("\\$", "", total_gross),
         total_gross = gsub(",", "", total_gross),
         total_gross = as.numeric(total_gross),
         open_gross = gsub("\\$", "", open_gross),
         open_gross = gsub(",", "", open_gross),
         open_gross = as.numeric(open_gross)) %>% 
  mutate(total_gross_millions = total_gross / 10^6,
         open_gross_millions = open_gross / 10^6) %>% 
  select(-total_gross, -revenue_millions, -open_gross) %>% 
  separate(., actors, c("actor1","actor2", "actor3", "actor4"), sep=",") %>% 
  separate(genre, into = c("genre1", "genre2", "genre3"), sep = ",")


```

----------------------------------------------------------------------------------------------------------------------------

# Jingxuan' s code:

## For review scores, can box office/genre/actor/director be indicators?

### Can box office be the indicator of review scores?
```{r}
set.seed(1)

movie_with_review_narm = 
  movie_with_boxoffice %>% 
  filter(!is.na(review_score)) 

# fit linear regression for review scoreand total gross
lm(review_score ~ total_gross_millions , data = movie_with_review_narm) %>% 
  summary() 

movie_with_review_narm %>% 
  ggplot(aes(x= total_gross_millions, y = review_score)) +
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") 
```

### Can genere be the indicator of review scores?
```{r}

```